services:
  api-extractor:
    build: ./system/services/api-extractor
    container_name: api-extractor
    env_file:
      - ./system/.env
    depends_on:
      api-llm:
        condition: service_started
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "8001:8001"
    restart: always
    networks:
      - app-network
  
  api-llm:
    build: ./system/services/api-llm
    container_name: api-llm
    env_file:
      - ./system/.env
    depends_on:
      - bd-vetorial
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "8002:8002"
    restart: always
    networks:
      - app-network

  api-telegram:
    build: ./system/services/api-telegram
    container_name: api-telegram
    env_file:
      - ./system/.env
    depends_on:
      api-llm:
        condition: service_started
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "8004:8004"
    restart: always
    networks:
      - app-network

  api-portal:
    build: ./system/services/api-portal
    container_name: api-portal
    env_file:
      - ./system/.env
    depends_on:
      api-llm:
        condition: service_started
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "8003:8003"
    restart: always
    networks:
      - app-network

  bd-vetorial:
    build: ./system/services/bd-vetorial
    container_name: bd-vetorial
    env_file:
      - ./system/.env
    depends_on:
      qdrant:
        condition: service_started
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "8005:8005"
    restart: always
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always
    networks:
      - app-network

  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    container_name: minio
    environment:
      TZ: "America/Sao_Paulo"
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - app-network

volumes:
  qdrant_storage:
    driver: local
  minio_data:
    driver: local

networks:
  app-network:
    driver: bridge